/*
 * AccidentInterface.java
 *
 * Created on 21/Nov/2011, 9:11:56
 */
import jadex.extension.envsupport.environment.IEnvironmentSpace;
import jadex.extension.envsupport.environment.ISpaceObject;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;

import jadex.extension.envsupport.environment.space2d.Space2D;
import jadex.extension.envsupport.math.IVector2;
import jadex.extension.envsupport.math.Vector2Int;

import javax.swing.table.AbstractTableModel;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;


public class LaunchConfig extends javax.swing.JFrame {

    private Space2D space;
    private ISpaceObject[] accidents = null;
    private ISpaceObject[] cells = null;
    private ISpaceObject[] homes = null;
    private ISpaceObject[] dests = null;
    private ISpaceObject[] pois = null;
   
    /** Creates new form AccidentInterface */
    public LaunchConfig(IEnvironmentSpace space) {
        this.space = (Space2D) space;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configura\u00E7\u00E3o do Ambiente");
        setResizable(false);
        
        accidents = space.getSpaceObjectsByType("accident");
        cells = space.getSpaceObjectsByType("cell");
        homes = space.getSpaceObjectsByType("homebase");
        dests = space.getSpaceObjectsByType("finaldestination");
        pois = space.getSpaceObjectsByType("pointofinterest");

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        lblEstadoDoTempo = new JLabel("Estado do tempo:");
        
        comboBoxTempo = new JComboBox();
        comboBoxTempo.addItem("Sol");
		comboBoxTempo.addItem("Chuva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jButton1)
        			.addGap(117)
        			.addComponent(lblEstadoDoTempo)
        			.addGap(18)
        			.addComponent(comboBoxTempo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(210))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(lblEstadoDoTempo)
        				.addComponent(comboBoxTempo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(512, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	BDIMap.start = true;
		space.setProperty("weather", comboBoxTempo.getSelectedItem().toString());
		
    }//GEN-LAST:event_jButton1ActionPerformed

    class MyTableModel extends AbstractTableModel {

        private String[] columnNames = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
            "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", 
            "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"};
        private Object[][] data = new Object[30][30];
        
        public int getColumnCount() {
            return columnNames.length;
        }

        public int getRowCount() {
            return data.length;
        }

        public String getColumnName(int col) {
            return columnNames[col];
        }

        public Object getValueAt(int row, int col) {
            return data[row][col];
        }

        /*
         * JTable uses this method to determine the default renderer/
         * editor for each cell.  If we didn't implement this method,
         * then the last column would contain text ("true"/"false"),
         * rather than a check box.
         */
        public Class getColumnClass(int c) {
            return getValueAt(0, c).getClass();
        }

        public boolean isCellEditable(int row, int col) {
            //Note that the data/cell address is constant,
            //no matter where the cell appears onscreen.

            return true;

        }

        public void setValueAt(Object value, int row, int col) {

            data[row][col] = value;
            fireTableCellUpdated(row, col);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private JLabel lblEstadoDoTempo;
    private JComboBox comboBoxTempo;
    // End of variables declaration//GEN-END:variables
}
